# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 807)
        MainWindow.setStyleSheet("background-color: #2f2d3c;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_tituloLogin = QtWidgets.QLabel(self.centralwidget)
        self.label_tituloLogin.setGeometry(QtCore.QRect(450, 30, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_tituloLogin.setFont(font)
        self.label_tituloLogin.setStyleSheet("color: #FAF8FF;")
        self.label_tituloLogin.setObjectName("label_tituloLogin")
        self.pushButton_voltarLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltarLogin.setGeometry(QtCore.QRect(30, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_voltarLogin.setFont(font)
        self.pushButton_voltarLogin.setStyleSheet("background-color: #3F3E73;\n"
"color: #FAF8FF;\n"
"border-radius: 8;\n"
"")
        self.pushButton_voltarLogin.setObjectName("pushButton_voltarLogin")
        self.label_subtituloLogin = QtWidgets.QLabel(self.centralwidget)
        self.label_subtituloLogin.setGeometry(QtCore.QRect(580, 280, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtituloLogin.setFont(font)
        self.label_subtituloLogin.setStyleSheet("color: #FAF8FF;")
        self.label_subtituloLogin.setObjectName("label_subtituloLogin")
        self.lineEdit_nomeLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nomeLogin.setGeometry(QtCore.QRect(370, 340, 551, 41))
        self.lineEdit_nomeLogin.setStyleSheet("background-color: #FAF8FF;")
        self.lineEdit_nomeLogin.setObjectName("lineEdit_nomeLogin")
        self.lineEdit_senhaLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senhaLogin.setGeometry(QtCore.QRect(370, 410, 551, 41))
        self.lineEdit_senhaLogin.setStyleSheet("background-color: #FAF8FF;")
        self.lineEdit_senhaLogin.setObjectName("lineEdit_senhaLogin")
        self.label_nomeLogin = QtWidgets.QLabel(self.centralwidget)
        self.label_nomeLogin.setGeometry(QtCore.QRect(290, 340, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nomeLogin.setFont(font)
        self.label_nomeLogin.setStyleSheet("color: #FAF8FF;")
        self.label_nomeLogin.setObjectName("label_nomeLogin")
        self.label_senhaLogin = QtWidgets.QLabel(self.centralwidget)
        self.label_senhaLogin.setGeometry(QtCore.QRect(290, 410, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_senhaLogin.setFont(font)
        self.label_senhaLogin.setStyleSheet("color: #FAF8FF;")
        self.label_senhaLogin.setObjectName("label_senhaLogin")
        self.pushButton_CancelarLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CancelarLogin.setGeometry(QtCore.QRect(660, 510, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_CancelarLogin.setFont(font)
        self.pushButton_CancelarLogin.setStyleSheet("background: #3F3E73;\n"
"color: white;\n"
"border-radius: 8;")
        self.pushButton_CancelarLogin.setObjectName("pushButton_CancelarLogin")
        self.pushButton_Login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Login.setGeometry(QtCore.QRect(430, 510, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Login.setFont(font)
        self.pushButton_Login.setStyleSheet("background: #8685EF;\n"
"color: white;\n"
"border-radius: 8;")
        self.pushButton_Login.setObjectName("pushButton_Login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_tituloLogin.setText(_translate("MainWindow", "ContaCerta"))
        self.pushButton_voltarLogin.setText(_translate("MainWindow", "Voltar"))
        self.label_subtituloLogin.setText(_translate("MainWindow", "Login"))
        self.label_nomeLogin.setText(_translate("MainWindow", "Nome:"))
        self.label_senhaLogin.setText(_translate("MainWindow", "Senha:"))
        self.pushButton_CancelarLogin.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_Login.setText(_translate("MainWindow", "Login"))
