# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 807)
        MainWindow.setStyleSheet("background-color: #2F2D3C;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_NomeLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_NomeLogin.setGeometry(QtCore.QRect(380, 280, 551, 41))
        self.lineEdit_NomeLogin.setStyleSheet("background: #FAF8FF;\n"
"border-radius: 8;")
        self.lineEdit_NomeLogin.setObjectName("lineEdit_NomeLogin")
        self.label_Titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_Titulo.setGeometry(QtCore.QRect(440, -1, 421, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_Titulo.setFont(font)
        self.label_Titulo.setStyleSheet("color: white;")
        self.label_Titulo.setObjectName("label_Titulo")
        self.pushButton_Logar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Logar.setGeometry(QtCore.QRect(440, 559, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Logar.setFont(font)
        self.pushButton_Logar.setStyleSheet("background: #8685EF;\n"
"color: white;\n"
"border-radius: 8;")
        self.pushButton_Logar.setObjectName("pushButton_Logar")
        self.label_NomeLogin = QtWidgets.QLabel(self.centralwidget)
        self.label_NomeLogin.setGeometry(QtCore.QRect(290, 279, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_NomeLogin.setFont(font)
        self.label_NomeLogin.setStyleSheet("color: white;")
        self.label_NomeLogin.setObjectName("label_NomeLogin")
        self.label_SenhaLogin = QtWidgets.QLabel(self.centralwidget)
        self.label_SenhaLogin.setGeometry(QtCore.QRect(290, 359, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_SenhaLogin.setFont(font)
        self.label_SenhaLogin.setStyleSheet("color: white;")
        self.label_SenhaLogin.setObjectName("label_SenhaLogin")
        self.pushButton_CancelarLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CancelarLogin.setGeometry(QtCore.QRect(670, 559, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_CancelarLogin.setFont(font)
        self.pushButton_CancelarLogin.setStyleSheet("background: #3F3E73;\n"
"color: white;\n"
"border-radius: 8;")
        self.pushButton_CancelarLogin.setObjectName("pushButton_CancelarLogin")
        self.pushButton_VoltarLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_VoltarLogin.setGeometry(QtCore.QRect(50, 19, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_VoltarLogin.setFont(font)
        self.pushButton_VoltarLogin.setStyleSheet("background: #3F3E73;\n"
"color: white;\n"
"border-radius: 8;")
        self.pushButton_VoltarLogin.setObjectName("pushButton_VoltarLogin")
        self.lineEdit_SenhaLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SenhaLogin.setGeometry(QtCore.QRect(380, 359, 551, 41))
        self.lineEdit_SenhaLogin.setStyleSheet("background: #FAF8FF;\n"
"border-radius: 8;")
        self.lineEdit_SenhaLogin.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_SenhaLogin.setObjectName("lineEdit_SenhaLogin")
        self.label_Login = QtWidgets.QLabel(self.centralwidget)
        self.label_Login.setGeometry(QtCore.QRect(600, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Login.setFont(font)
        self.label_Login.setStyleSheet("color: white;")
        self.label_Login.setObjectName("label_Login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Titulo.setText(_translate("MainWindow", " ContaCerta"))
        self.pushButton_Logar.setText(_translate("MainWindow", "Login"))
        self.label_NomeLogin.setText(_translate("MainWindow", "Nome:"))
        self.label_SenhaLogin.setText(_translate("MainWindow", "Senha:"))
        self.pushButton_CancelarLogin.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_VoltarLogin.setText(_translate("MainWindow", "Voltar"))
        self.label_Login.setText(_translate("MainWindow", "Login"))
