# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instrucoes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 807)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #2F2D3C;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 30, 401, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FAF8FF")
        self.label.setObjectName("label")
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(100, 210, 1061, 511))
        self.columnView.setStyleSheet("background-color: #8A84B0;\n"
"border-radius: 8\n"
"")
        self.columnView.setObjectName("columnView")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(30, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voltar.setStyleSheet("background-color:#3F3E73;\n"
"color: #FAF8FF;\n"
"border-radius: 8;")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.pushButton_comecar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_comecar.setGeometry(QtCore.QRect(980, 730, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_comecar.setFont(font)
        self.pushButton_comecar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_comecar.setStyleSheet("color: #FAF8FF;\n"
"background-color:#3F3E73;\n"
"border-radius: 8;")
        self.pushButton_comecar.setObjectName("pushButton_comecar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 270, 1031, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #FAF8FF; background-color:#8A84B0;\n"
"text-align: justify;")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 220, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FAF8FF; background-color:#8A84B0")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 140, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FAF8FF")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Conta Certa"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
        self.pushButton_comecar.setText(_translate("MainWindow", "Começar!"))
        self.label_2.setText(_translate("MainWindow", "Assim que você iniciar o jogo, uma equação aleatória será exibida na tela — e o cronômetro começará a contar! ⏱️\n"
"\n"
"Ao longo da partida, novas equações surgirão de forma aleatória. Sua missão é resolvê-las o mais rápido possível:\n"
"✅ Acertou? Ganha 10 pontos! ❌ Errou? Não ganha nada — então capriche na resposta!\n"
"\n"
"A pontuação é zerada a cada nova partida, mas o seu recorde pessoal ficará salvo na sua conta (que você precisa criar ou estar logado para jogar).\n"
"Esse recorde pode ser superado sempre que quiser!\n"
"📈 Quanto mais pontos você fizer em menos tempo, melhor será sua colocação no ranking!"))
        self.label_3.setText(_translate("MainWindow", "🎮 Como Funciona o Jogo?"))
        self.label_4.setText(_translate("MainWindow", "Instruções"))
