# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pause.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 807)
        MainWindow.setStyleSheet("background-color: #2F2D3C;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_tituloPause = QtWidgets.QLabel(self.centralwidget)
        self.label_tituloPause.setGeometry(QtCore.QRect(430, 40, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_tituloPause.setFont(font)
        self.label_tituloPause.setStyleSheet("color: #FAF8FF;")
        self.label_tituloPause.setObjectName("label_tituloPause")
        self.pushButton_continuePause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_continuePause.setGeometry(QtCore.QRect(520, 310, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_continuePause.setFont(font)
        self.pushButton_continuePause.setStyleSheet("background-color: #8685EF;\n"
"border-radius: 8;\n"
"color:#FAF8FF;")
        self.pushButton_continuePause.setObjectName("pushButton_continuePause")
        self.label_subtituloPause = QtWidgets.QLabel(self.centralwidget)
        self.label_subtituloPause.setGeometry(QtCore.QRect(560, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtituloPause.setFont(font)
        self.label_subtituloPause.setStyleSheet("color: #FAF8FF;")
        self.label_subtituloPause.setObjectName("label_subtituloPause")
        self.pushButton_sairPause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sairPause.setGeometry(QtCore.QRect(520, 380, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sairPause.setFont(font)
        self.pushButton_sairPause.setStyleSheet("background-color: #3F3E73;\n"
"border-radius: 8;\n"
"color:#FAF8FF;")
        self.pushButton_sairPause.setObjectName("pushButton_sairPause")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_tituloPause.setText(_translate("MainWindow", "ContaCerta"))
        self.pushButton_continuePause.setText(_translate("MainWindow", "Continue"))
        self.label_subtituloPause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_sairPause.setText(_translate("MainWindow", "Sair"))
