# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ranking.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 807)
        MainWindow.setStyleSheet("background:#2F2D3C;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_Titulo.setGeometry(QtCore.QRect(440, 20, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_Titulo.setFont(font)
        self.label_Titulo.setStyleSheet("color:#FAF8FF;")
        self.label_Titulo.setObjectName("label_Titulo")
        self.label_subtitulo = QtWidgets.QLabel(self.centralwidget)
        self.label_subtitulo.setGeometry(QtCore.QRect(560, 120, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_subtitulo.setFont(font)
        self.label_subtitulo.setStyleSheet("color:#FAF8FF;")
        self.label_subtitulo.setObjectName("label_subtitulo")
        self.label_titulos = QtWidgets.QLabel(self.centralwidget)
        self.label_titulos.setGeometry(QtCore.QRect(50, 210, 1151, 81))
        self.label_titulos.setStyleSheet("background:#3F3E73;\n"
"border-radius: 5px;")
        self.label_titulos.setText("")
        self.label_titulos.setObjectName("label_titulos")
        self.label_primeiroLugar = QtWidgets.QLabel(self.centralwidget)
        self.label_primeiroLugar.setGeometry(QtCore.QRect(50, 290, 1151, 81))
        self.label_primeiroLugar.setStyleSheet("background:#736E95;\n"
"border-radius: 5px;")
        self.label_primeiroLugar.setText("")
        self.label_primeiroLugar.setObjectName("label_primeiroLugar")
        self.label_segundoLugar = QtWidgets.QLabel(self.centralwidget)
        self.label_segundoLugar.setGeometry(QtCore.QRect(50, 370, 1151, 81))
        self.label_segundoLugar.setStyleSheet("background:#8A84B0;\n"
"border-radius: 5px;")
        self.label_segundoLugar.setText("")
        self.label_segundoLugar.setObjectName("label_segundoLugar")
        self.label_quartoLugar = QtWidgets.QLabel(self.centralwidget)
        self.label_quartoLugar.setGeometry(QtCore.QRect(50, 530, 1151, 81))
        self.label_quartoLugar.setStyleSheet("background:#8A84B0;\n"
"border-radius: 5px;")
        self.label_quartoLugar.setText("")
        self.label_quartoLugar.setObjectName("label_quartoLugar")
        self.label_terceiroLugar = QtWidgets.QLabel(self.centralwidget)
        self.label_terceiroLugar.setGeometry(QtCore.QRect(50, 450, 1151, 81))
        self.label_terceiroLugar.setStyleSheet("background:#736E95;\n"
"border-radius: 5px;")
        self.label_terceiroLugar.setText("")
        self.label_terceiroLugar.setObjectName("label_terceiroLugar")
        self.label_sextoLugar = QtWidgets.QLabel(self.centralwidget)
        self.label_sextoLugar.setGeometry(QtCore.QRect(50, 690, 1151, 81))
        self.label_sextoLugar.setStyleSheet("background:#8A84B0;\n"
"border-radius: 5px;")
        self.label_sextoLugar.setText("")
        self.label_sextoLugar.setObjectName("label_sextoLugar")
        self.label_quintoLugar = QtWidgets.QLabel(self.centralwidget)
        self.label_quintoLugar.setGeometry(QtCore.QRect(50, 610, 1151, 81))
        self.label_quintoLugar.setStyleSheet("background:#736E95;\n"
"border-radius: 5px;")
        self.label_quintoLugar.setText("")
        self.label_quintoLugar.setObjectName("label_quintoLugar")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Voltar.setGeometry(QtCore.QRect(50, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Voltar.setFont(font)
        self.pushButton_Voltar.setStyleSheet("background:#3F3E73;\n"
"border-radius: 8px;\n"
"color: #FAF8FF;")
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.label_posicao = QtWidgets.QLabel(self.centralwidget)
        self.label_posicao.setGeometry(QtCore.QRect(110, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicao.setFont(font)
        self.label_posicao.setStyleSheet("background:#3F3E73;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicao.setObjectName("label_posicao")
        self.label_nome_do_jogador = QtWidgets.QLabel(self.centralwidget)
        self.label_nome_do_jogador.setGeometry(QtCore.QRect(380, 230, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nome_do_jogador.setFont(font)
        self.label_nome_do_jogador.setStyleSheet("background:#3F3E73;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nome_do_jogador.setObjectName("label_nome_do_jogador")
        self.label_pontuacao = QtWidgets.QLabel(self.centralwidget)
        self.label_pontuacao.setGeometry(QtCore.QRect(760, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontuacao.setFont(font)
        self.label_pontuacao.setStyleSheet("background:#3F3E73;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_pontuacao.setObjectName("label_pontuacao")
        self.label_tempo = QtWidgets.QLabel(self.centralwidget)
        self.label_tempo.setGeometry(QtCore.QRect(1060, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempo.setFont(font)
        self.label_tempo.setStyleSheet("background:#3F3E73;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempo.setObjectName("label_tempo")
        self.label_posicaoPrimeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_posicaoPrimeiro.setGeometry(QtCore.QRect(110, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicaoPrimeiro.setFont(font)
        self.label_posicaoPrimeiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicaoPrimeiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posicaoPrimeiro.setObjectName("label_posicaoPrimeiro")
        self.label_posicaoSegundo = QtWidgets.QLabel(self.centralwidget)
        self.label_posicaoSegundo.setGeometry(QtCore.QRect(110, 390, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicaoSegundo.setFont(font)
        self.label_posicaoSegundo.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicaoSegundo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posicaoSegundo.setObjectName("label_posicaoSegundo")
        self.label_posicaoTerceiro = QtWidgets.QLabel(self.centralwidget)
        self.label_posicaoTerceiro.setGeometry(QtCore.QRect(110, 470, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicaoTerceiro.setFont(font)
        self.label_posicaoTerceiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicaoTerceiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posicaoTerceiro.setObjectName("label_posicaoTerceiro")
        self.label_posicaoQuinto = QtWidgets.QLabel(self.centralwidget)
        self.label_posicaoQuinto.setGeometry(QtCore.QRect(110, 630, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicaoQuinto.setFont(font)
        self.label_posicaoQuinto.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicaoQuinto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posicaoQuinto.setObjectName("label_posicaoQuinto")
        self.label_posicaoQuarto = QtWidgets.QLabel(self.centralwidget)
        self.label_posicaoQuarto.setGeometry(QtCore.QRect(110, 550, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicaoQuarto.setFont(font)
        self.label_posicaoQuarto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicaoQuarto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posicaoQuarto.setObjectName("label_posicaoQuarto")
        self.label_posicaoSexto = QtWidgets.QLabel(self.centralwidget)
        self.label_posicaoSexto.setGeometry(QtCore.QRect(110, 710, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_posicaoSexto.setFont(font)
        self.label_posicaoSexto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_posicaoSexto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posicaoSexto.setObjectName("label_posicaoSexto")
        self.label_tempoSegundo = QtWidgets.QLabel(self.centralwidget)
        self.label_tempoSegundo.setGeometry(QtCore.QRect(1060, 390, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempoSegundo.setFont(font)
        self.label_tempoSegundo.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempoSegundo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempoSegundo.setObjectName("label_tempoSegundo")
        self.label_tempoPrimeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_tempoPrimeiro.setGeometry(QtCore.QRect(1060, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempoPrimeiro.setFont(font)
        self.label_tempoPrimeiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempoPrimeiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempoPrimeiro.setObjectName("label_tempoPrimeiro")
        self.label_tempoTerceiro = QtWidgets.QLabel(self.centralwidget)
        self.label_tempoTerceiro.setGeometry(QtCore.QRect(1060, 470, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempoTerceiro.setFont(font)
        self.label_tempoTerceiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempoTerceiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempoTerceiro.setObjectName("label_tempoTerceiro")
        self.label_tempoQuinto = QtWidgets.QLabel(self.centralwidget)
        self.label_tempoQuinto.setGeometry(QtCore.QRect(1060, 630, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempoQuinto.setFont(font)
        self.label_tempoQuinto.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempoQuinto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempoQuinto.setObjectName("label_tempoQuinto")
        self.label_tempoQuarto = QtWidgets.QLabel(self.centralwidget)
        self.label_tempoQuarto.setGeometry(QtCore.QRect(1060, 550, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempoQuarto.setFont(font)
        self.label_tempoQuarto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempoQuarto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempoQuarto.setObjectName("label_tempoQuarto")
        self.label_tempoSexto = QtWidgets.QLabel(self.centralwidget)
        self.label_tempoSexto.setGeometry(QtCore.QRect(1060, 710, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_tempoSexto.setFont(font)
        self.label_tempoSexto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_tempoSexto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tempoSexto.setObjectName("label_tempoSexto")
        self.label_nomePrimeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_nomePrimeiro.setGeometry(QtCore.QRect(360, 310, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nomePrimeiro.setFont(font)
        self.label_nomePrimeiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nomePrimeiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nomePrimeiro.setObjectName("label_nomePrimeiro")
        self.label_nomeTerceiro = QtWidgets.QLabel(self.centralwidget)
        self.label_nomeTerceiro.setGeometry(QtCore.QRect(360, 470, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nomeTerceiro.setFont(font)
        self.label_nomeTerceiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nomeTerceiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nomeTerceiro.setObjectName("label_nomeTerceiro")
        self.label_nomeQuinto = QtWidgets.QLabel(self.centralwidget)
        self.label_nomeQuinto.setGeometry(QtCore.QRect(360, 630, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nomeQuinto.setFont(font)
        self.label_nomeQuinto.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nomeQuinto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nomeQuinto.setObjectName("label_nomeQuinto")
        self.label_nomeSegundo = QtWidgets.QLabel(self.centralwidget)
        self.label_nomeSegundo.setGeometry(QtCore.QRect(360, 390, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nomeSegundo.setFont(font)
        self.label_nomeSegundo.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nomeSegundo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nomeSegundo.setObjectName("label_nomeSegundo")
        self.label_nomeQuarto = QtWidgets.QLabel(self.centralwidget)
        self.label_nomeQuarto.setGeometry(QtCore.QRect(360, 550, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nomeQuarto.setFont(font)
        self.label_nomeQuarto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nomeQuarto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nomeQuarto.setObjectName("label_nomeQuarto")
        self.label_nomeSexto = QtWidgets.QLabel(self.centralwidget)
        self.label_nomeSexto.setGeometry(QtCore.QRect(360, 710, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nomeSexto.setFont(font)
        self.label_nomeSexto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_nomeSexto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nomeSexto.setObjectName("label_nomeSexto")
        self.label_pontuacaoPrimeiro = QtWidgets.QLabel(self.centralwidget)
        self.label_pontuacaoPrimeiro.setGeometry(QtCore.QRect(750, 310, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontuacaoPrimeiro.setFont(font)
        self.label_pontuacaoPrimeiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_pontuacaoPrimeiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pontuacaoPrimeiro.setObjectName("label_pontuacaoPrimeiro")
        self.label_pontuacaoSegundo = QtWidgets.QLabel(self.centralwidget)
        self.label_pontuacaoSegundo.setGeometry(QtCore.QRect(750, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontuacaoSegundo.setFont(font)
        self.label_pontuacaoSegundo.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"")
        self.label_pontuacaoSegundo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pontuacaoSegundo.setObjectName("label_pontuacaoSegundo")
        self.label_pontuacaoQuarto = QtWidgets.QLabel(self.centralwidget)
        self.label_pontuacaoQuarto.setGeometry(QtCore.QRect(750, 550, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontuacaoQuarto.setFont(font)
        self.label_pontuacaoQuarto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"")
        self.label_pontuacaoQuarto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pontuacaoQuarto.setObjectName("label_pontuacaoQuarto")
        self.label_pontucaoSexto = QtWidgets.QLabel(self.centralwidget)
        self.label_pontucaoSexto.setGeometry(QtCore.QRect(750, 710, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontucaoSexto.setFont(font)
        self.label_pontucaoSexto.setStyleSheet("background:#8A84B0;\n"
"color:#FAF8FF;\n"
"")
        self.label_pontucaoSexto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pontucaoSexto.setObjectName("label_pontucaoSexto")
        self.label_pontuacaoTerceiro = QtWidgets.QLabel(self.centralwidget)
        self.label_pontuacaoTerceiro.setGeometry(QtCore.QRect(750, 470, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontuacaoTerceiro.setFont(font)
        self.label_pontuacaoTerceiro.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_pontuacaoTerceiro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pontuacaoTerceiro.setObjectName("label_pontuacaoTerceiro")
        self.label_pontuacaoQuinto = QtWidgets.QLabel(self.centralwidget)
        self.label_pontuacaoQuinto.setGeometry(QtCore.QRect(750, 630, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_pontuacaoQuinto.setFont(font)
        self.label_pontuacaoQuinto.setStyleSheet("background:#736E95;\n"
"color:#FAF8FF;\n"
"\n"
"")
        self.label_pontuacaoQuinto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pontuacaoQuinto.setObjectName("label_pontuacaoQuinto")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Titulo.setText(_translate("MainWindow", "ContaCerta"))
        self.label_subtitulo.setText(_translate("MainWindow", "Ranking"))
        self.pushButton_Voltar.setText(_translate("MainWindow", "Voltar"))
        self.label_posicao.setText(_translate("MainWindow", "Posição"))
        self.label_nome_do_jogador.setText(_translate("MainWindow", "Nome do Jogador"))
        self.label_pontuacao.setText(_translate("MainWindow", "Pontuação"))
        self.label_tempo.setText(_translate("MainWindow", "Tempo"))
        self.label_posicaoPrimeiro.setText(_translate("MainWindow", "1"))
        self.label_posicaoSegundo.setText(_translate("MainWindow", "1"))
        self.label_posicaoTerceiro.setText(_translate("MainWindow", "1"))
        self.label_posicaoQuinto.setText(_translate("MainWindow", "1"))
        self.label_posicaoQuarto.setText(_translate("MainWindow", "1"))
        self.label_posicaoSexto.setText(_translate("MainWindow", "1"))
        self.label_tempoSegundo.setText(_translate("MainWindow", "5:40"))
        self.label_tempoPrimeiro.setText(_translate("MainWindow", "5:40"))
        self.label_tempoTerceiro.setText(_translate("MainWindow", "5:40"))
        self.label_tempoQuinto.setText(_translate("MainWindow", "5:40"))
        self.label_tempoQuarto.setText(_translate("MainWindow", "5:40"))
        self.label_tempoSexto.setText(_translate("MainWindow", "5:40"))
        self.label_nomePrimeiro.setText(_translate("MainWindow", "Anna Laurah"))
        self.label_nomeTerceiro.setText(_translate("MainWindow", "Anna Laurah"))
        self.label_nomeQuinto.setText(_translate("MainWindow", "Anna Laurah"))
        self.label_nomeSegundo.setText(_translate("MainWindow", "Anna Laurah"))
        self.label_nomeQuarto.setText(_translate("MainWindow", "Anna Laurah"))
        self.label_nomeSexto.setText(_translate("MainWindow", "Anna Laurah"))
        self.label_pontuacaoPrimeiro.setText(_translate("MainWindow", "1000"))
        self.label_pontuacaoSegundo.setText(_translate("MainWindow", "1000"))
        self.label_pontuacaoQuarto.setText(_translate("MainWindow", "1000"))
        self.label_pontucaoSexto.setText(_translate("MainWindow", "1000"))
        self.label_pontuacaoTerceiro.setText(_translate("MainWindow", "1000"))
        self.label_pontuacaoQuinto.setText(_translate("MainWindow", "1000"))
