# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preJogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 806)
        MainWindow.setStyleSheet("background-color:rgb(47, 45, 60);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(435, 230, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(250, 248, 255);")
        self.label.setObjectName("label")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(534, 380, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.play_button.setFont(font)
        self.play_button.setStyleSheet("background-color: rgb(134, 133, 239);\n"
"color: rgb(250, 248, 255);\n"
"border-radius:8px;\n"
"width:260px;")
        self.play_button.setObjectName("play_button")
        self.ranking_button = QtWidgets.QPushButton(self.centralwidget)
        self.ranking_button.setGeometry(QtCore.QRect(534, 440, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ranking_button.setFont(font)
        self.ranking_button.setStyleSheet("color: rgb(250, 248, 255);\n"
"background-color: rgb(63, 62, 115);\n"
"border-radius:8px;")
        self.ranking_button.setObjectName("ranking_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(30, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("color: rgb(250, 248, 255);\n"
"background-color: rgb(63, 62, 115);\n"
"border-radius:8px;")
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ContaCerta"))
        self.play_button.setText(_translate("MainWindow", "Jogar"))
        self.ranking_button.setText(_translate("MainWindow", "Ranking"))
        self.exit_button.setText(_translate("MainWindow", "Sair da Conta"))
